### PR TITLE
Add movie recommender

### PR DESCRIPTION
**Pull request by Hsankesara**

### CODE REVIEW

**Comment by Hsankesara** [comment]
Why Travis build failed because of k-means?

**Comment by shivamsaboo17** [comment]
capture


Try writing the future import on the first line of the code

**Comment by Hsankesara** [comment]
I should not do anything with k-means as it is not part of this project. that is why i opened another issue and it would be good if someone wanna get assigned on it

**Comment by shivamsaboo17** [comment]
@Hsankesara the build is failing due to timeout.
Please check if the output is being displayed properly.

**Comment by Hsankesara** [comment]
The programme basically takes a review from the user and then give appropriate output. So how can I change it @shivamsaboo17? Any Suggestions??

**Comment by Hsankesara** [comment]
Someone, please add label  Hacktoberfest on this PR.

**Comment by shivamsaboo17** [comment]
@Hsankesara make a test file and take input from there. See this article for more details:
https://stackoverflow.com/questions/37107609/how-to-test-a-project-that-need-keyboard-input-with-travis-ci-org

**Comment by Hsankesara** [comment]
Ok, I will make necessary changes. :+1:

**Pull request merged**
