### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by khilanravani**

### CODE REVIEW

**Comment by khilanravani** [comment]
@guru-DeV-002 Please help with the newline issue at the end of file. Donno why it is happening.

**Comment by shivamsaboo17** [comment]
Fixed the newline at the end just check @khilanravani

**Comment by khilanravani** [comment]
@shivamsaboo17 I don't think that it is fixed. Did u view the file? (View Changes)

**Comment by shivamsaboo17** [comment]
@khilanravani  there was a newline at the end which has been removed. What else needs to be fixed?

**Comment by khilanravani** [comment]
@shivamsaboo17 ok. Please try merging it. We will get to know if there's still an issue.

**Comment by khilanravani** [comment]
@shivamsaboo17 Got the issue now? :sweat_smile:

**Pull request merged**
