### PR TITLE
Travis CI and .editorconfig files added

### PR DESCRIPTION
**Pull request by Hsankesara**
Please review it and tell me if any changes needed

### CODE REVIEW

**Comment by Hsankesara** [comment]
I'll make necessary changes  @khilanravani

**Comment by shivamsaboo17** [comment]
@Hsankesara  why are you re-merging logistic regression in this pr?

**Comment by Hsankesara** [comment]
It's not duplicate @shivamsaboo17 I just change folder name as it is required.

**Comment by Hsankesara** [comment]
@shivamsaboo17 both of your regression algorithms does not give any output that is why Travis build is failing. can you please do necessary changes and commit it here.

**Comment by shivamsaboo17** [comment]
@Hsankesara  I am displaying the graph in the end and the program runs until the graph is closed manually. What should I do? 
I can not show the graph then and just print the hypothesis.
Would that be okay?

**Comment by Hsankesara** [comment]
you can use ```time.sleep(t)``` to display graph for t seconds and then close it and print hypothesis function.

**Comment by Hsankesara** [comment]
please take t<= 5 sec or Travis will show error.

**Comment by shivamsaboo17** [comment]
Got it.
But it gives a warning : MatplotlibDeprecationWarning
So I am using 
`warnings.filterwarnings("ignore",category=matplotlib.cbook.mplDeprecation)`
to supress it.
Is it okay?

**Comment by Hsankesara** [comment]
jt'll be fine @shivamsaboo17

**Comment by Hsankesara** [comment]
Hey @khilanravani @guru-DeV-002 @shivamsaboo17 , please review it and tell me any feature you like to add or any changes required.

**Comment by anshumanv** [comment]
Are bhai pyara. :bowing_man: :clap: :tada:

**Comment by shivamsaboo17** [comment]
@anshumanv TT khelega?

**Comment by anshumanv** [comment]
Aaja @shivamsaboo17 instant.

**Pull request merged**
